language: rust
rust:
- nightly
cache:
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"
script:
- cargo build
os:
- linux
- osx
notifications:
  email:
    on_success: never
branches:
  only:
  - master
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $(uname -s) = Linux ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: Z6XpYFIhaXHX98gfeqEZ5P643JjUs4SxSqXEdGHFeKmxcMtxTGFStOEdf3usVFD5NeL32qGLro4g8Hx+nPAAzdFPTIpyXwWLaChP9ARkmMFGO7dpro0mxyBtNrglVjVM6yY5sviD8QCA8EB5GhwF5X0Z1G/5+GpyqG2KlQ/8ETkFhBQ5RJwUcTwtQ8OvtI+PwECPW47zao0xEJYlj3wTbguNLT8h9Kj3h9XHFZr5KrrfE8mrqQaYFoMab1BD/RcxQEDpKfvQC4CAmdoEZQnAukvHtt8L2vXEsI7zY0NMDxyXTsRkFmSuJInkvThOPAvFUYEN1GN4tpJY8LuS8OS1/c2CsqhltReDKD4ONkZukoH53mo1oz/fNDqKWlUMGkW+DYHbgccqHC1iPsG34qNoIPjkbKyIpduzTdeccOIO/DZobbwZp7Omw9kUjjOy7aRgn5Ba4EieEM7VHOhby3jMfFCsBhZ6YmzJvmvgoBt5GsIZsx24GTAsu8svamCGjwLaF15i7uMrpSsIEMHZ/LNw5kVbCLuDUYqz+jtwCyV3C5P3X3avVyINvRyfTqOpfmtB2692wIenKU0yMApLGBPjCWJbMPAc5NYurZAdtfdQqQkU4cFf3bV8+EP1Xb9Eth4eri+GyGhMT+3blqn5XHaXDRqwEFi9wF2pZsKvwQyhODI=
