[package]
name = "rust_cast"
description = "Library that allows you to communicate with Google Cast enabled devices (e.g. Chromecast)."
documentation = "https://azasypkin.github.io/rust-cast/"
homepage = "https://github.com/azasypkin/rust-cast"
repository = "https://github.com/azasypkin/rust-cast"
readme = "README.md"
license = "MIT"
keywords = ["cast", "chromecast", "google"]
version = "0.13.2"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
categories = ["api-bindings", "hardware-support", "multimedia"]

[dependencies]
byteorder = "1.2.4"
log = "0.4.3"
openssl = "0.10.11"
protobuf = "2.0.4"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"

[build-dependencies]
protoc-rust = "2.0.4"
