[package]
name = "rust_cast"
description = "Library that allows you to communicate with Google Cast enabled devices (e.g. Chromecast)."
documentation = "https://azasypkin.github.io/rust-cast/"
homepage = "https://github.com/azasypkin/rust-cast"
repository = "https://github.com/azasypkin/rust-cast"
readme = "README.md"
license = "MIT"
keywords = ["cast", "chromecast", "google"]
version = "0.11.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
exclude = ["protobuf/*"]
categories = ["api-bindings", "hardware-support", "multimedia"]

[dependencies]
byteorder = "1.2.1"
log = "0.4.1"
openssl = "0.10.2"
protobuf = "1.4.3"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
