[package]
name = "rust_cast"
description = "Library that allows you to communicate with Google Cast enabled devices (e.g. Chromecast)."
documentation = "https://azasypkin.github.io/rust-cast/"
homepage = "https://github.com/azasypkin/rust-cast"
repository = "https://github.com/azasypkin/rust-cast"
readme = "README.md"
license = "MIT"
keywords = ["cast", "chromecast", "google"]
version = "0.8.2"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
exclude = ["protobuf/*"]
build = "build.rs"

[dependencies]
byteorder = "1.0.0"
log = "0.3.6"
openssl = "0.9.7"
protobuf = "1.2.2"
serde = "0.9.11"
serde_json = "0.9.9"

[build-dependencies]
serde_codegen = "0.9.0"