[package]
name = "chromecast_link"
version = "0.2.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
openssl = "0.7.13"
protobuf = "1.0.22"
serde = "0.7.11"
serde_json = "0.7.3"
serde_macros = "0.7.11"
