[package]
name = "chromecast_link"
version = "0.1.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
openssl = "0.7.13"
protobuf = "1.0.21"
serde = "0.7.6"
serde_json = "0.7.1"
serde_macros = "0.7.5"
