name: Rust Cast CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Build (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Check format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Build (default features)
        with:
          command: build
          args: --release --examples

      - uses: actions-rs/cargo@v1
        name: Build (thread-safe feature)
        with:
          command: build
          args: --release --examples --features thread_safe

      - uses: actions-rs/cargo@v1
        name: Test (default features)
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Test (thread-safe feature)
        with:
          command: test
          args: --features thread_safe

  ci-osx:
    name: Build (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [ stable, beta, nightly ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1
        name: Build (default features)
        with:
          command: build
          args: --release --examples

      - uses: actions-rs/cargo@v1
        name: Build (thread-safe feature)
        with:
          command: build
          args: --release --examples --features thread_safe

  ci-osx-arm:
    if: ${{ false }}
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        target: [aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        name: Build (default features)
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --examples

      - uses: actions-rs/cargo@v1
        name: Build (thread-safe feature)
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --examples --features thread_safe

  ci-build-docs:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all

      - name: Create index.html
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=rust_cast\">" > ./target/doc/index.html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
